### ISSUE TITLE
Characteristic None not found!

### ISSUE THREAD

**Issue by RayBytes** [Bluetooth-Devices/led-ble#35]
```
Traceback (most recent call last):
  File "/Users/name/Projects/RGB/main.py", line 54, in <module>
    asyncio.run(run())
  File "/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/name/Projects/RGB/main.py", line 36, in run
    await led.update()
  File "/opt/homebrew/lib/python3.10/site-packages/led_ble/led_ble.py", line 150, in update
    await self._ensure_connected()
  File "/opt/homebrew/lib/python3.10/site-packages/led_ble/led_ble.py", line 355, in _ensure_connected
    await client.start_notify(self._read_char, self._notification_handler)
  File "/opt/homebrew/lib/python3.10/site-packages/bleak/__init__.py", line 639, in start_notify
    raise BleakError(f"Characteristic {char_specifier} not found!")
bleak.exc.BleakError: Characteristic None not found!
```
I've gotten the above error when running the example code. 
<img width="724" alt="Screenshot 2023-03-17 at 12 43 47 PM" src="https://user-images.githubusercontent.com/108236317/225843143-2340661f-e308-4fbb-a329-bdd73ef8f5d7.png">

I had found this address and set it to the ADDRESS variable and it connected then gave that error

Here are the logs before the error:

```
INFO:__main__:Detected: 32544AB4-2034-EB5D-85B8-E59AF0BBD3C1: ELK-BLEDOM
INFO:__main__:Found device: 32544AB4-2034-EB5D-85B8-E59AF0BBD3C1
DEBUG:led_ble.led_ble:ELK-BLEDOM: Connecting; RSSI: None
DEBUG:led_ble.led_ble:ELK-BLEDOM: Connected; RSSI: None
/opt/homebrew/lib/python3.10/site-packages/led_ble/led_ble.py:347: FutureWarning: This method will be removed future version, use the services property instead.
  resolved = self._resolve_characteristics(await client.get_services())
DEBUG:led_ble.led_ble:ELK-BLEDOM: Subscribe to notifications; RSSI: None
```

**Comment by notexpected** [comment]
This bug seems related to a [HomeAssistant bug](https://github.com/home-assistant/core/issues/121563)

Looking at the code a bit, I believe this call:

```
File "/opt/homebrew/lib/python3.10/site-packages/led_ble/led_ble.py", line 355, in _ensure_connected
    await client.start_notify(self._read_char, self._notification_handler)
```

is happening when client.services is not valid and the self._read_char is still None.

Note, [get_services](https://bleak.readthedocs.io/en/latest/_modules/bleak.html#BleakClient.get_services) is deprecated.

**Comment by bdraco** [comment]
This design is pretty old. It needs to be re-written.
